// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/moikot/smartthings-go/client/apps"
	"github.com/moikot/smartthings-go/client/capabilities"
	"github.com/moikot/smartthings-go/client/deviceprofiles"
	"github.com/moikot/smartthings-go/client/devices"
	"github.com/moikot/smartthings-go/client/installedapps"
	"github.com/moikot/smartthings-go/client/locations"
	"github.com/moikot/smartthings-go/client/presentations"
	"github.com/moikot/smartthings-go/client/rooms"
	"github.com/moikot/smartthings-go/client/rules"
	"github.com/moikot/smartthings-go/client/scenes"
	"github.com/moikot/smartthings-go/client/schedules"
	"github.com/moikot/smartthings-go/client/subscriptions"
)

// Default smart things API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.smartthings.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new smart things API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SmartThingsAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new smart things API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *SmartThingsAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new smart things API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SmartThingsAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(SmartThingsAPI)
	cli.Transport = transport
	cli.Apps = apps.New(transport, formats)
	cli.Capabilities = capabilities.New(transport, formats)
	cli.Deviceprofiles = deviceprofiles.New(transport, formats)
	cli.Devices = devices.New(transport, formats)
	cli.Installedapps = installedapps.New(transport, formats)
	cli.Locations = locations.New(transport, formats)
	cli.Presentations = presentations.New(transport, formats)
	cli.Rooms = rooms.New(transport, formats)
	cli.Rules = rules.New(transport, formats)
	cli.Scenes = scenes.New(transport, formats)
	cli.Schedules = schedules.New(transport, formats)
	cli.Subscriptions = subscriptions.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// SmartThingsAPI is a client for smart things API
type SmartThingsAPI struct {
	Apps apps.ClientService

	Capabilities capabilities.ClientService

	Deviceprofiles deviceprofiles.ClientService

	Devices devices.ClientService

	Installedapps installedapps.ClientService

	Locations locations.ClientService

	Presentations presentations.ClientService

	Rooms rooms.ClientService

	Rules rules.ClientService

	Scenes scenes.ClientService

	Schedules schedules.ClientService

	Subscriptions subscriptions.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SmartThingsAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Apps.SetTransport(transport)
	c.Capabilities.SetTransport(transport)
	c.Deviceprofiles.SetTransport(transport)
	c.Devices.SetTransport(transport)
	c.Installedapps.SetTransport(transport)
	c.Locations.SetTransport(transport)
	c.Presentations.SetTransport(transport)
	c.Rooms.SetTransport(transport)
	c.Rules.SetTransport(transport)
	c.Scenes.SetTransport(transport)
	c.Schedules.SetTransport(transport)
	c.Subscriptions.SetTransport(transport)
}
