// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moikot/smartthings-go/models"
)

// ListRulesReader is a Reader for the ListRules structure.
type ListRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListRulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListRulesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListRulesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListRulesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListRulesOK creates a ListRulesOK with default headers values
func NewListRulesOK() *ListRulesOK {
	return &ListRulesOK{}
}

/*ListRulesOK handles this case with default header values.

A paginated list of rules.
*/
type ListRulesOK struct {
	Payload *models.PagedRules
}

func (o *ListRulesOK) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesOK  %+v", 200, o.Payload)
}

func (o *ListRulesOK) GetPayload() *models.PagedRules {
	return o.Payload
}

func (o *ListRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedRules)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRulesBadRequest creates a ListRulesBadRequest with default headers values
func NewListRulesBadRequest() *ListRulesBadRequest {
	return &ListRulesBadRequest{}
}

/*ListRulesBadRequest handles this case with default header values.

Bad request
*/
type ListRulesBadRequest struct {
}

func (o *ListRulesBadRequest) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesBadRequest ", 400)
}

func (o *ListRulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListRulesUnauthorized creates a ListRulesUnauthorized with default headers values
func NewListRulesUnauthorized() *ListRulesUnauthorized {
	return &ListRulesUnauthorized{}
}

/*ListRulesUnauthorized handles this case with default header values.

Not authenticated
*/
type ListRulesUnauthorized struct {
}

func (o *ListRulesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesUnauthorized ", 401)
}

func (o *ListRulesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListRulesForbidden creates a ListRulesForbidden with default headers values
func NewListRulesForbidden() *ListRulesForbidden {
	return &ListRulesForbidden{}
}

/*ListRulesForbidden handles this case with default header values.

Not authorized or not found
*/
type ListRulesForbidden struct {
}

func (o *ListRulesForbidden) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesForbidden ", 403)
}

func (o *ListRulesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListRulesDefault creates a ListRulesDefault with default headers values
func NewListRulesDefault(code int) *ListRulesDefault {
	return &ListRulesDefault{
		_statusCode: code,
	}
}

/*ListRulesDefault handles this case with default header values.

Unexpected error
*/
type ListRulesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list rules default response
func (o *ListRulesDefault) Code() int {
	return o._statusCode
}

func (o *ListRulesDefault) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRules default  %+v", o._statusCode, o.Payload)
}

func (o *ListRulesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListRulesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
