// Code generated by go-swagger; DO NOT EDIT.

package deviceprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListDeviceProfilesParams creates a new ListDeviceProfilesParams object
// with the default values initialized.
func NewListDeviceProfilesParams() *ListDeviceProfilesParams {
	var ()
	return &ListDeviceProfilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDeviceProfilesParamsWithTimeout creates a new ListDeviceProfilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDeviceProfilesParamsWithTimeout(timeout time.Duration) *ListDeviceProfilesParams {
	var ()
	return &ListDeviceProfilesParams{

		timeout: timeout,
	}
}

// NewListDeviceProfilesParamsWithContext creates a new ListDeviceProfilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDeviceProfilesParamsWithContext(ctx context.Context) *ListDeviceProfilesParams {
	var ()
	return &ListDeviceProfilesParams{

		Context: ctx,
	}
}

// NewListDeviceProfilesParamsWithHTTPClient creates a new ListDeviceProfilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDeviceProfilesParamsWithHTTPClient(client *http.Client) *ListDeviceProfilesParams {
	var ()
	return &ListDeviceProfilesParams{
		HTTPClient: client,
	}
}

/*ListDeviceProfilesParams contains all the parameters to send to the API endpoint
for the list device profiles operation typically these are written to a http.Request
*/
type ListDeviceProfilesParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*ProfileID
	  The device profiles IDs to filter the results by.


	*/
	ProfileID []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list device profiles params
func (o *ListDeviceProfilesParams) WithTimeout(timeout time.Duration) *ListDeviceProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list device profiles params
func (o *ListDeviceProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list device profiles params
func (o *ListDeviceProfilesParams) WithContext(ctx context.Context) *ListDeviceProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list device profiles params
func (o *ListDeviceProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list device profiles params
func (o *ListDeviceProfilesParams) WithHTTPClient(client *http.Client) *ListDeviceProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list device profiles params
func (o *ListDeviceProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the list device profiles params
func (o *ListDeviceProfilesParams) WithAuthorization(authorization string) *ListDeviceProfilesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the list device profiles params
func (o *ListDeviceProfilesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithProfileID adds the profileID to the list device profiles params
func (o *ListDeviceProfilesParams) WithProfileID(profileID []string) *ListDeviceProfilesParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the list device profiles params
func (o *ListDeviceProfilesParams) SetProfileID(profileID []string) {
	o.ProfileID = profileID
}

// WriteToRequest writes these params to a swagger request
func (o *ListDeviceProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	valuesProfileID := o.ProfileID

	joinedProfileID := swag.JoinByFormat(valuesProfileID, "multi")
	// query array param profileId
	if err := r.SetQueryParam("profileId", joinedProfileID...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
