// Code generated by go-swagger; DO NOT EDIT.

package rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moikot/smartthings-go/models"
)

// ListRoomsReader is a Reader for the ListRooms structure.
type ListRoomsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRoomsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRoomsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListRoomsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListRoomsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListRoomsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListRoomsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListRoomsOK creates a ListRoomsOK with default headers values
func NewListRoomsOK() *ListRoomsOK {
	return &ListRoomsOK{}
}

/*ListRoomsOK handles this case with default header values.

An array of Rooms
*/
type ListRoomsOK struct {
	Payload *models.PagedRooms
}

func (o *ListRoomsOK) Error() string {
	return fmt.Sprintf("[GET /locations/{locationId}/rooms][%d] listRoomsOK  %+v", 200, o.Payload)
}

func (o *ListRoomsOK) GetPayload() *models.PagedRooms {
	return o.Payload
}

func (o *ListRoomsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedRooms)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRoomsUnauthorized creates a ListRoomsUnauthorized with default headers values
func NewListRoomsUnauthorized() *ListRoomsUnauthorized {
	return &ListRoomsUnauthorized{}
}

/*ListRoomsUnauthorized handles this case with default header values.

Unauthorized
*/
type ListRoomsUnauthorized struct {
}

func (o *ListRoomsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /locations/{locationId}/rooms][%d] listRoomsUnauthorized ", 401)
}

func (o *ListRoomsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListRoomsForbidden creates a ListRoomsForbidden with default headers values
func NewListRoomsForbidden() *ListRoomsForbidden {
	return &ListRoomsForbidden{}
}

/*ListRoomsForbidden handles this case with default header values.

Forbidden
*/
type ListRoomsForbidden struct {
}

func (o *ListRoomsForbidden) Error() string {
	return fmt.Sprintf("[GET /locations/{locationId}/rooms][%d] listRoomsForbidden ", 403)
}

func (o *ListRoomsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListRoomsTooManyRequests creates a ListRoomsTooManyRequests with default headers values
func NewListRoomsTooManyRequests() *ListRoomsTooManyRequests {
	return &ListRoomsTooManyRequests{}
}

/*ListRoomsTooManyRequests handles this case with default header values.

Too many requests
*/
type ListRoomsTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *ListRoomsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /locations/{locationId}/rooms][%d] listRoomsTooManyRequests  %+v", 429, o.Payload)
}

func (o *ListRoomsTooManyRequests) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListRoomsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRoomsDefault creates a ListRoomsDefault with default headers values
func NewListRoomsDefault(code int) *ListRoomsDefault {
	return &ListRoomsDefault{
		_statusCode: code,
	}
}

/*ListRoomsDefault handles this case with default header values.

Unexpected error
*/
type ListRoomsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list rooms default response
func (o *ListRoomsDefault) Code() int {
	return o._statusCode
}

func (o *ListRoomsDefault) Error() string {
	return fmt.Sprintf("[GET /locations/{locationId}/rooms][%d] listRooms default  %+v", o._statusCode, o.Payload)
}

func (o *ListRoomsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListRoomsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
