// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/moikot/smartthings-go/models"
)

// NewRegisterParams creates a new RegisterParams object
// with the default values initialized.
func NewRegisterParams() *RegisterParams {
	var ()
	return &RegisterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterParamsWithTimeout creates a new RegisterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegisterParamsWithTimeout(timeout time.Duration) *RegisterParams {
	var ()
	return &RegisterParams{

		timeout: timeout,
	}
}

// NewRegisterParamsWithContext creates a new RegisterParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegisterParamsWithContext(ctx context.Context) *RegisterParams {
	var ()
	return &RegisterParams{

		Context: ctx,
	}
}

// NewRegisterParamsWithHTTPClient creates a new RegisterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegisterParamsWithHTTPClient(client *http.Client) *RegisterParams {
	var ()
	return &RegisterParams{
		HTTPClient: client,
	}
}

/*RegisterParams contains all the parameters to send to the API endpoint
for the register operation typically these are written to a http.Request
*/
type RegisterParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*AppNameOrID
	  The appName or appId field of an app.

	*/
	AppNameOrID string
	/*AppRegisterRequest*/
	AppRegisterRequest models.AppRegisterRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the register params
func (o *RegisterParams) WithTimeout(timeout time.Duration) *RegisterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register params
func (o *RegisterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register params
func (o *RegisterParams) WithContext(ctx context.Context) *RegisterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register params
func (o *RegisterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register params
func (o *RegisterParams) WithHTTPClient(client *http.Client) *RegisterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register params
func (o *RegisterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the register params
func (o *RegisterParams) WithAuthorization(authorization string) *RegisterParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the register params
func (o *RegisterParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAppNameOrID adds the appNameOrID to the register params
func (o *RegisterParams) WithAppNameOrID(appNameOrID string) *RegisterParams {
	o.SetAppNameOrID(appNameOrID)
	return o
}

// SetAppNameOrID adds the appNameOrId to the register params
func (o *RegisterParams) SetAppNameOrID(appNameOrID string) {
	o.AppNameOrID = appNameOrID
}

// WithAppRegisterRequest adds the appRegisterRequest to the register params
func (o *RegisterParams) WithAppRegisterRequest(appRegisterRequest models.AppRegisterRequest) *RegisterParams {
	o.SetAppRegisterRequest(appRegisterRequest)
	return o
}

// SetAppRegisterRequest adds the appRegisterRequest to the register params
func (o *RegisterParams) SetAppRegisterRequest(appRegisterRequest models.AppRegisterRequest) {
	o.AppRegisterRequest = appRegisterRequest
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param appNameOrId
	if err := r.SetPathParam("appNameOrId", o.AppNameOrID); err != nil {
		return err
	}

	if o.AppRegisterRequest != nil {
		if err := r.SetBodyParam(o.AppRegisterRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
