// Code generated by go-swagger; DO NOT EDIT.

package presentations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/moikot/smartthings-go/models"
)

// NewCreateCustomCapabilityPresentationParams creates a new CreateCustomCapabilityPresentationParams object
// with the default values initialized.
func NewCreateCustomCapabilityPresentationParams() *CreateCustomCapabilityPresentationParams {
	var ()
	return &CreateCustomCapabilityPresentationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCustomCapabilityPresentationParamsWithTimeout creates a new CreateCustomCapabilityPresentationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCustomCapabilityPresentationParamsWithTimeout(timeout time.Duration) *CreateCustomCapabilityPresentationParams {
	var ()
	return &CreateCustomCapabilityPresentationParams{

		timeout: timeout,
	}
}

// NewCreateCustomCapabilityPresentationParamsWithContext creates a new CreateCustomCapabilityPresentationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCustomCapabilityPresentationParamsWithContext(ctx context.Context) *CreateCustomCapabilityPresentationParams {
	var ()
	return &CreateCustomCapabilityPresentationParams{

		Context: ctx,
	}
}

// NewCreateCustomCapabilityPresentationParamsWithHTTPClient creates a new CreateCustomCapabilityPresentationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCustomCapabilityPresentationParamsWithHTTPClient(client *http.Client) *CreateCustomCapabilityPresentationParams {
	var ()
	return &CreateCustomCapabilityPresentationParams{
		HTTPClient: client,
	}
}

/*CreateCustomCapabilityPresentationParams contains all the parameters to send to the API endpoint
for the create custom capability presentation operation typically these are written to a http.Request
*/
type CreateCustomCapabilityPresentationParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*CapabilityID
	  The ID of the capability.

	*/
	CapabilityID string
	/*CapabilityVersion
	  The version of the capability

	*/
	CapabilityVersion int64
	/*CreateCustomCapabilityPresentationRequest*/
	CreateCustomCapabilityPresentationRequest *models.CreateCapabilityPresentationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithTimeout(timeout time.Duration) *CreateCustomCapabilityPresentationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithContext(ctx context.Context) *CreateCustomCapabilityPresentationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithHTTPClient(client *http.Client) *CreateCustomCapabilityPresentationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithAuthorization(authorization string) *CreateCustomCapabilityPresentationParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithCapabilityID adds the capabilityID to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithCapabilityID(capabilityID string) *CreateCustomCapabilityPresentationParams {
	o.SetCapabilityID(capabilityID)
	return o
}

// SetCapabilityID adds the capabilityId to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetCapabilityID(capabilityID string) {
	o.CapabilityID = capabilityID
}

// WithCapabilityVersion adds the capabilityVersion to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithCapabilityVersion(capabilityVersion int64) *CreateCustomCapabilityPresentationParams {
	o.SetCapabilityVersion(capabilityVersion)
	return o
}

// SetCapabilityVersion adds the capabilityVersion to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetCapabilityVersion(capabilityVersion int64) {
	o.CapabilityVersion = capabilityVersion
}

// WithCreateCustomCapabilityPresentationRequest adds the createCustomCapabilityPresentationRequest to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) WithCreateCustomCapabilityPresentationRequest(createCustomCapabilityPresentationRequest *models.CreateCapabilityPresentationRequest) *CreateCustomCapabilityPresentationParams {
	o.SetCreateCustomCapabilityPresentationRequest(createCustomCapabilityPresentationRequest)
	return o
}

// SetCreateCustomCapabilityPresentationRequest adds the createCustomCapabilityPresentationRequest to the create custom capability presentation params
func (o *CreateCustomCapabilityPresentationParams) SetCreateCustomCapabilityPresentationRequest(createCustomCapabilityPresentationRequest *models.CreateCapabilityPresentationRequest) {
	o.CreateCustomCapabilityPresentationRequest = createCustomCapabilityPresentationRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCustomCapabilityPresentationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param capabilityId
	if err := r.SetPathParam("capabilityId", o.CapabilityID); err != nil {
		return err
	}

	// path param capabilityVersion
	if err := r.SetPathParam("capabilityVersion", swag.FormatInt64(o.CapabilityVersion)); err != nil {
		return err
	}

	if o.CreateCustomCapabilityPresentationRequest != nil {
		if err := r.SetBodyParam(o.CreateCustomCapabilityPresentationRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
