// Code generated by go-swagger; DO NOT EDIT.

package presentations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/moikot/smartthings-go/models"
)

// GetCustomCapabilityPresentationReader is a Reader for the GetCustomCapabilityPresentation structure.
type GetCustomCapabilityPresentationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomCapabilityPresentationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomCapabilityPresentationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCustomCapabilityPresentationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCustomCapabilityPresentationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCustomCapabilityPresentationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetCustomCapabilityPresentationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetCustomCapabilityPresentationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCustomCapabilityPresentationOK creates a GetCustomCapabilityPresentationOK with default headers values
func NewGetCustomCapabilityPresentationOK() *GetCustomCapabilityPresentationOK {
	return &GetCustomCapabilityPresentationOK{}
}

/*GetCustomCapabilityPresentationOK handles this case with default header values.

successful return of a capability presentation
*/
type GetCustomCapabilityPresentationOK struct {
	/*Maximum requests allowed within the rate limit window.
	 */
	XRateLimitLimit int64
	/*Remaining requests available within the window.
	 */
	XRateLimitRemaining int64
	/*Time in milliseconds until the current window expires.
	 */
	XRateLimitReset int64

	Payload *models.CapabilityPresentation
}

func (o *GetCustomCapabilityPresentationOK) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentationOK  %+v", 200, o.Payload)
}

func (o *GetCustomCapabilityPresentationOK) GetPayload() *models.CapabilityPresentation {
	return o.Payload
}

func (o *GetCustomCapabilityPresentationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-RateLimit-Limit
	xRateLimitLimit, err := swag.ConvertInt64(response.GetHeader("X-RateLimit-Limit"))
	if err != nil {
		return errors.InvalidType("X-RateLimit-Limit", "header", "int64", response.GetHeader("X-RateLimit-Limit"))
	}
	o.XRateLimitLimit = xRateLimitLimit

	// response header X-RateLimit-Remaining
	xRateLimitRemaining, err := swag.ConvertInt64(response.GetHeader("X-RateLimit-Remaining"))
	if err != nil {
		return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", response.GetHeader("X-RateLimit-Remaining"))
	}
	o.XRateLimitRemaining = xRateLimitRemaining

	// response header X-RateLimit-Reset
	xRateLimitReset, err := swag.ConvertInt64(response.GetHeader("X-RateLimit-Reset"))
	if err != nil {
		return errors.InvalidType("X-RateLimit-Reset", "header", "int64", response.GetHeader("X-RateLimit-Reset"))
	}
	o.XRateLimitReset = xRateLimitReset

	o.Payload = new(models.CapabilityPresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomCapabilityPresentationUnauthorized creates a GetCustomCapabilityPresentationUnauthorized with default headers values
func NewGetCustomCapabilityPresentationUnauthorized() *GetCustomCapabilityPresentationUnauthorized {
	return &GetCustomCapabilityPresentationUnauthorized{}
}

/*GetCustomCapabilityPresentationUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCustomCapabilityPresentationUnauthorized struct {
}

func (o *GetCustomCapabilityPresentationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentationUnauthorized ", 401)
}

func (o *GetCustomCapabilityPresentationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCustomCapabilityPresentationForbidden creates a GetCustomCapabilityPresentationForbidden with default headers values
func NewGetCustomCapabilityPresentationForbidden() *GetCustomCapabilityPresentationForbidden {
	return &GetCustomCapabilityPresentationForbidden{}
}

/*GetCustomCapabilityPresentationForbidden handles this case with default header values.

Forbidden
*/
type GetCustomCapabilityPresentationForbidden struct {
}

func (o *GetCustomCapabilityPresentationForbidden) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentationForbidden ", 403)
}

func (o *GetCustomCapabilityPresentationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCustomCapabilityPresentationNotFound creates a GetCustomCapabilityPresentationNotFound with default headers values
func NewGetCustomCapabilityPresentationNotFound() *GetCustomCapabilityPresentationNotFound {
	return &GetCustomCapabilityPresentationNotFound{}
}

/*GetCustomCapabilityPresentationNotFound handles this case with default header values.

Not found
*/
type GetCustomCapabilityPresentationNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetCustomCapabilityPresentationNotFound) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentationNotFound  %+v", 404, o.Payload)
}

func (o *GetCustomCapabilityPresentationNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetCustomCapabilityPresentationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomCapabilityPresentationTooManyRequests creates a GetCustomCapabilityPresentationTooManyRequests with default headers values
func NewGetCustomCapabilityPresentationTooManyRequests() *GetCustomCapabilityPresentationTooManyRequests {
	return &GetCustomCapabilityPresentationTooManyRequests{}
}

/*GetCustomCapabilityPresentationTooManyRequests handles this case with default header values.

Too many requests
*/
type GetCustomCapabilityPresentationTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *GetCustomCapabilityPresentationTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentationTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetCustomCapabilityPresentationTooManyRequests) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetCustomCapabilityPresentationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomCapabilityPresentationDefault creates a GetCustomCapabilityPresentationDefault with default headers values
func NewGetCustomCapabilityPresentationDefault(code int) *GetCustomCapabilityPresentationDefault {
	return &GetCustomCapabilityPresentationDefault{
		_statusCode: code,
	}
}

/*GetCustomCapabilityPresentationDefault handles this case with default header values.

Unexpected error
*/
type GetCustomCapabilityPresentationDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get custom capability presentation default response
func (o *GetCustomCapabilityPresentationDefault) Code() int {
	return o._statusCode
}

func (o *GetCustomCapabilityPresentationDefault) Error() string {
	return fmt.Sprintf("[GET /capabilities/{capabilityId}/{capabilityVersion}/presentation][%d] getCustomCapabilityPresentation default  %+v", o._statusCode, o.Payload)
}

func (o *GetCustomCapabilityPresentationDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetCustomCapabilityPresentationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
