// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ArgumentName Argument name of a command
//
// swagger:model argumentName
type ArgumentName string

// Validate validates this argument name
func (m ArgumentName) Validate(formats strfmt.Registry) error {
	return nil
}
