// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateDeviceConfigRequest create device config request
//
// swagger:model CreateDeviceConfigRequest
type CreateDeviceConfigRequest struct {

	// automation
	Automation *CreateDeviceConfigRequestAutomation `json:"automation,omitempty"`

	// dashboard
	Dashboard *CreateDeviceConfigRequestDashboard `json:"dashboard,omitempty"`

	// detail view
	DetailView []*DeviceConfigEntry `json:"detailView"`

	// icon Url
	IconURL IconURL `json:"iconUrl,omitempty"`

	// type
	// Enum: [dth profile]
	Type *string `json:"type,omitempty"`
}

// Validate validates this create device config request
func (m *CreateDeviceConfigRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutomation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDashboard(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDetailView(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIconURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateDeviceConfigRequest) validateAutomation(formats strfmt.Registry) error {

	if swag.IsZero(m.Automation) { // not required
		return nil
	}

	if m.Automation != nil {
		if err := m.Automation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("automation")
			}
			return err
		}
	}

	return nil
}

func (m *CreateDeviceConfigRequest) validateDashboard(formats strfmt.Registry) error {

	if swag.IsZero(m.Dashboard) { // not required
		return nil
	}

	if m.Dashboard != nil {
		if err := m.Dashboard.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dashboard")
			}
			return err
		}
	}

	return nil
}

func (m *CreateDeviceConfigRequest) validateDetailView(formats strfmt.Registry) error {

	if swag.IsZero(m.DetailView) { // not required
		return nil
	}

	for i := 0; i < len(m.DetailView); i++ {
		if swag.IsZero(m.DetailView[i]) { // not required
			continue
		}

		if m.DetailView[i] != nil {
			if err := m.DetailView[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("detailView" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateDeviceConfigRequest) validateIconURL(formats strfmt.Registry) error {

	if swag.IsZero(m.IconURL) { // not required
		return nil
	}

	if err := m.IconURL.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("iconUrl")
		}
		return err
	}

	return nil
}

var createDeviceConfigRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dth","profile"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createDeviceConfigRequestTypeTypePropEnum = append(createDeviceConfigRequestTypeTypePropEnum, v)
	}
}

const (

	// CreateDeviceConfigRequestTypeDth captures enum value "dth"
	CreateDeviceConfigRequestTypeDth string = "dth"

	// CreateDeviceConfigRequestTypeProfile captures enum value "profile"
	CreateDeviceConfigRequestTypeProfile string = "profile"
)

// prop value enum
func (m *CreateDeviceConfigRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createDeviceConfigRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateDeviceConfigRequest) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateDeviceConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateDeviceConfigRequest) UnmarshalBinary(b []byte) error {
	var res CreateDeviceConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateDeviceConfigRequestAutomation create device config request automation
//
// swagger:model CreateDeviceConfigRequestAutomation
type CreateDeviceConfigRequestAutomation struct {

	// actions
	Actions []*DeviceConfigEntry `json:"actions"`

	// conditions
	Conditions []*DeviceConfigEntry `json:"conditions"`
}

// Validate validates this create device config request automation
func (m *CreateDeviceConfigRequestAutomation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConditions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateDeviceConfigRequestAutomation) validateActions(formats strfmt.Registry) error {

	if swag.IsZero(m.Actions) { // not required
		return nil
	}

	for i := 0; i < len(m.Actions); i++ {
		if swag.IsZero(m.Actions[i]) { // not required
			continue
		}

		if m.Actions[i] != nil {
			if err := m.Actions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("automation" + "." + "actions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateDeviceConfigRequestAutomation) validateConditions(formats strfmt.Registry) error {

	if swag.IsZero(m.Conditions) { // not required
		return nil
	}

	for i := 0; i < len(m.Conditions); i++ {
		if swag.IsZero(m.Conditions[i]) { // not required
			continue
		}

		if m.Conditions[i] != nil {
			if err := m.Conditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("automation" + "." + "conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateDeviceConfigRequestAutomation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateDeviceConfigRequestAutomation) UnmarshalBinary(b []byte) error {
	var res CreateDeviceConfigRequestAutomation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateDeviceConfigRequestDashboard create device config request dashboard
//
// swagger:model CreateDeviceConfigRequestDashboard
type CreateDeviceConfigRequestDashboard struct {

	// actions
	Actions []*DeviceConfigEntry `json:"actions"`

	// states
	States []*DeviceConfigEntry `json:"states"`
}

// Validate validates this create device config request dashboard
func (m *CreateDeviceConfigRequestDashboard) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateDeviceConfigRequestDashboard) validateActions(formats strfmt.Registry) error {

	if swag.IsZero(m.Actions) { // not required
		return nil
	}

	for i := 0; i < len(m.Actions); i++ {
		if swag.IsZero(m.Actions[i]) { // not required
			continue
		}

		if m.Actions[i] != nil {
			if err := m.Actions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dashboard" + "." + "actions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateDeviceConfigRequestDashboard) validateStates(formats strfmt.Registry) error {

	if swag.IsZero(m.States) { // not required
		return nil
	}

	for i := 0; i < len(m.States); i++ {
		if swag.IsZero(m.States[i]) { // not required
			continue
		}

		if m.States[i] != nil {
			if err := m.States[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dashboard" + "." + "states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateDeviceConfigRequestDashboard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateDeviceConfigRequestDashboard) UnmarshalBinary(b []byte) error {
	var res CreateDeviceConfigRequestDashboard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
