// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// DateReference date reference
//
// swagger:model DateReference
type DateReference string

const (

	// DateReferenceToday captures enum value "Today"
	DateReferenceToday DateReference = "Today"
)

// for schema
var dateReferenceEnum []interface{}

func init() {
	var res []DateReference
	if err := json.Unmarshal([]byte(`["Today"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dateReferenceEnum = append(dateReferenceEnum, v)
	}
}

func (m DateReference) validateDateReferenceEnum(path, location string, value DateReference) error {
	if err := validate.EnumCase(path, location, value, dateReferenceEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this date reference
func (m DateReference) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDateReferenceEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
