// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DossierDevicePresentation dossier device presentation
//
// swagger:model DossierDevicePresentation
type DossierDevicePresentation struct {

	// automation
	Automation *Automation `json:"automation,omitempty"`

	// dashboard
	Dashboard *Dashboard `json:"dashboard,omitempty"`

	// detail view
	DetailView DetailView `json:"detailView,omitempty"`

	// dp info
	// Required: true
	DpInfo DpInfo `json:"dpInfo"`

	// icon Url
	IconURL IconURL `json:"iconUrl,omitempty"`

	// language
	Language Language `json:"language,omitempty"`

	// Secondary namespacing key for grouping presentations (formerly `mnmn`)
	// Required: true
	ManufacturerName *string `json:"manufacturerName"`

	// DEPRECATED: Secondary namespacing key for grouping presentations
	Mnmn string `json:"mnmn,omitempty"`

	// System generated identifier that corresponds to a device presentation (formerly `vid`)
	// Required: true
	PresentationID *string `json:"presentationId"`

	// DEPRECATED: System generated identifier that corresponds to a device presentation
	Vid string `json:"vid,omitempty"`
}

// Validate validates this dossier device presentation
func (m *DossierDevicePresentation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutomation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDashboard(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDetailView(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDpInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIconURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLanguage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateManufacturerName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePresentationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DossierDevicePresentation) validateAutomation(formats strfmt.Registry) error {

	if swag.IsZero(m.Automation) { // not required
		return nil
	}

	if m.Automation != nil {
		if err := m.Automation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("automation")
			}
			return err
		}
	}

	return nil
}

func (m *DossierDevicePresentation) validateDashboard(formats strfmt.Registry) error {

	if swag.IsZero(m.Dashboard) { // not required
		return nil
	}

	if m.Dashboard != nil {
		if err := m.Dashboard.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dashboard")
			}
			return err
		}
	}

	return nil
}

func (m *DossierDevicePresentation) validateDetailView(formats strfmt.Registry) error {

	if swag.IsZero(m.DetailView) { // not required
		return nil
	}

	if err := m.DetailView.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("detailView")
		}
		return err
	}

	return nil
}

func (m *DossierDevicePresentation) validateDpInfo(formats strfmt.Registry) error {

	if err := validate.Required("dpInfo", "body", m.DpInfo); err != nil {
		return err
	}

	if err := m.DpInfo.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("dpInfo")
		}
		return err
	}

	return nil
}

func (m *DossierDevicePresentation) validateIconURL(formats strfmt.Registry) error {

	if swag.IsZero(m.IconURL) { // not required
		return nil
	}

	if err := m.IconURL.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("iconUrl")
		}
		return err
	}

	return nil
}

func (m *DossierDevicePresentation) validateLanguage(formats strfmt.Registry) error {

	if swag.IsZero(m.Language) { // not required
		return nil
	}

	if err := m.Language.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("language")
		}
		return err
	}

	return nil
}

func (m *DossierDevicePresentation) validateManufacturerName(formats strfmt.Registry) error {

	if err := validate.Required("manufacturerName", "body", m.ManufacturerName); err != nil {
		return err
	}

	return nil
}

func (m *DossierDevicePresentation) validatePresentationID(formats strfmt.Registry) error {

	if err := validate.Required("presentationId", "body", m.PresentationID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DossierDevicePresentation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DossierDevicePresentation) UnmarshalBinary(b []byte) error {
	var res DossierDevicePresentation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
