// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExcludedDeviceActionConfigEntry excluded device action config entry
//
// swagger:model excludedDeviceActionConfigEntry
type ExcludedDeviceActionConfigEntry struct {
	DeviceConfigEntry

	// To exclude specified automation in `exclude` when this item is selected by the user.
	Exclusion []*ExcludedActionItemID `json:"exclusion"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExcludedDeviceActionConfigEntry) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 DeviceConfigEntry
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.DeviceConfigEntry = aO0

	// AO1
	var dataAO1 struct {
		Exclusion []*ExcludedActionItemID `json:"exclusion"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Exclusion = dataAO1.Exclusion

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExcludedDeviceActionConfigEntry) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.DeviceConfigEntry)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Exclusion []*ExcludedActionItemID `json:"exclusion"`
	}

	dataAO1.Exclusion = m.Exclusion

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this excluded device action config entry
func (m *ExcludedDeviceActionConfigEntry) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DeviceConfigEntry
	if err := m.DeviceConfigEntry.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExclusion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExcludedDeviceActionConfigEntry) validateExclusion(formats strfmt.Registry) error {

	if swag.IsZero(m.Exclusion) { // not required
		return nil
	}

	for i := 0; i < len(m.Exclusion); i++ {
		if swag.IsZero(m.Exclusion[i]) { // not required
			continue
		}

		if m.Exclusion[i] != nil {
			if err := m.Exclusion[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("exclusion" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExcludedDeviceActionConfigEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExcludedDeviceActionConfigEntry) UnmarshalBinary(b []byte) error {
	var res ExcludedDeviceActionConfigEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
