// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExcludedConditionItemID excluded condition item Id
//
// swagger:model excludedConditionItemId
type ExcludedConditionItemID struct {

	// The index of the array in the given capability to which this exclusion object will be inserted
	ID int64 `json:"id,omitempty"`

	ExcludedConditionItem
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExcludedConditionItemID) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		ID int64 `json:"id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.ID = dataAO0.ID

	// AO1
	var aO1 ExcludedConditionItem
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ExcludedConditionItem = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExcludedConditionItemID) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		ID int64 `json:"id,omitempty"`
	}

	dataAO0.ID = m.ID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	aO1, err := swag.WriteJSON(m.ExcludedConditionItem)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this excluded condition item Id
func (m *ExcludedConditionItemID) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ExcludedConditionItem
	if err := m.ExcludedConditionItem.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ExcludedConditionItemID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExcludedConditionItemID) UnmarshalBinary(b []byte) error {
	var res ExcludedConditionItemID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
