// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// IconURL Preloaded iconId or URL used to retrieve icons to be drawn on the UI Client.
//
// swagger:model iconUrl
type IconURL string

// Validate validates this icon Url
func (m IconURL) Validate(formats strfmt.Registry) error {
	return nil
}
