// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MessageConfig A message configuration.
//
// swagger:model MessageConfig
type MessageConfig struct {

	// The key value of the message group.
	MessageGroupKey string `json:"messageGroupKey,omitempty"`
}

// Validate validates this message config
func (m *MessageConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MessageConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessageConfig) UnmarshalBinary(b []byte) error {
	var res MessageConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
