// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Notice notice
//
// swagger:model Notice
type Notice struct {

	// The action(s) a user can take to resolve this notice
	Actions []NoticeAction `json:"actions"`

	// The url of the badge icon for the notice card
	BadgeURL string `json:"badgeUrl,omitempty"`

	// code
	Code NoticeCode `json:"code,omitempty"`

	// The localized message to be displayed
	Message string `json:"message,omitempty"`
}

// Validate validates this notice
func (m *Notice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Notice) validateActions(formats strfmt.Registry) error {

	if swag.IsZero(m.Actions) { // not required
		return nil
	}

	for i := 0; i < len(m.Actions); i++ {

		if err := m.Actions[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("actions" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *Notice) validateCode(formats strfmt.Registry) error {

	if swag.IsZero(m.Code) { // not required
		return nil
	}

	if err := m.Code.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("code")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Notice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Notice) UnmarshalBinary(b []byte) error {
	var res Notice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
