// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OperandAggregationMode operand aggregation mode
//
// swagger:model OperandAggregationMode
type OperandAggregationMode string

const (

	// OperandAggregationModeNone captures enum value "None"
	OperandAggregationModeNone OperandAggregationMode = "None"
)

// for schema
var operandAggregationModeEnum []interface{}

func init() {
	var res []OperandAggregationMode
	if err := json.Unmarshal([]byte(`["None"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operandAggregationModeEnum = append(operandAggregationModeEnum, v)
	}
}

func (m OperandAggregationMode) validateOperandAggregationModeEnum(path, location string, value OperandAggregationMode) error {
	if err := validate.EnumCase(path, location, value, operandAggregationModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this operand aggregation mode
func (m OperandAggregationMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOperandAggregationModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
