// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchItem patch item
//
// swagger:model patchItem
type PatchItem struct {

	// Operation objects MUST have exactly one "op" member, whose value indicates the operation to perform
	// Required: true
	// Enum: [add replace remove]
	Op *string `json:"op"`

	// path specifies a string format for identifying a specific value within a JSON document. It is used by all operations in patch to specify the part of the document to operate on.
	// Required: true
	Path *string `json:"path"`

	// value
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this patch item
func (m *PatchItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var patchItemTypeOpPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["add","replace","remove"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		patchItemTypeOpPropEnum = append(patchItemTypeOpPropEnum, v)
	}
}

const (

	// PatchItemOpAdd captures enum value "add"
	PatchItemOpAdd string = "add"

	// PatchItemOpReplace captures enum value "replace"
	PatchItemOpReplace string = "replace"

	// PatchItemOpRemove captures enum value "remove"
	PatchItemOpRemove string = "remove"
)

// prop value enum
func (m *PatchItem) validateOpEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, patchItemTypeOpPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PatchItem) validateOp(formats strfmt.Registry) error {

	if err := validate.Required("op", "body", m.Op); err != nil {
		return err
	}

	// value enum
	if err := m.validateOpEnum("op", "body", *m.Op); err != nil {
		return err
	}

	return nil
}

func (m *PatchItem) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("path", "body", m.Path); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchItem) UnmarshalBinary(b []byte) error {
	var res PatchItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
