// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SceneSecurityModeRequest The security mode to be activated by the Scene
//
// swagger:model SceneSecurityModeRequest
type SceneSecurityModeRequest struct {

	// the id of the action to be created. Optional, sent by Reaver only
	ActionID string `json:"actionId,omitempty"`

	// Additional query param
	Arguments string `json:"arguments,omitempty"`

	// The id of the security mode
	// Required: true
	// Enum: [setArmStay setArmAway disarm]
	Security *string `json:"security"`
}

// Validate validates this scene security mode request
func (m *SceneSecurityModeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecurity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sceneSecurityModeRequestTypeSecurityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["setArmStay","setArmAway","disarm"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sceneSecurityModeRequestTypeSecurityPropEnum = append(sceneSecurityModeRequestTypeSecurityPropEnum, v)
	}
}

const (

	// SceneSecurityModeRequestSecuritySetArmStay captures enum value "setArmStay"
	SceneSecurityModeRequestSecuritySetArmStay string = "setArmStay"

	// SceneSecurityModeRequestSecuritySetArmAway captures enum value "setArmAway"
	SceneSecurityModeRequestSecuritySetArmAway string = "setArmAway"

	// SceneSecurityModeRequestSecurityDisarm captures enum value "disarm"
	SceneSecurityModeRequestSecurityDisarm string = "disarm"
)

// prop value enum
func (m *SceneSecurityModeRequest) validateSecurityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sceneSecurityModeRequestTypeSecurityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SceneSecurityModeRequest) validateSecurity(formats strfmt.Registry) error {

	if err := validate.Required("security", "body", m.Security); err != nil {
		return err
	}

	// value enum
	if err := m.validateSecurityEnum("security", "body", *m.Security); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SceneSecurityModeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SceneSecurityModeRequest) UnmarshalBinary(b []byte) error {
	var res SceneSecurityModeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
