// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StandbyPowerSwitchForDashboard standby power switch for dashboard
//
// swagger:model standbyPowerSwitchForDashboard
type StandbyPowerSwitchForDashboard struct {
	SwitchForDashboard

	StandbyPowerSwitchForDashboardAllOf1

	StandbyPowerSwitchForDashboardAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *StandbyPowerSwitchForDashboard) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SwitchForDashboard
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SwitchForDashboard = aO0

	// AO1
	var aO1 StandbyPowerSwitchForDashboardAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.StandbyPowerSwitchForDashboardAllOf1 = aO1

	// AO2
	var aO2 StandbyPowerSwitchForDashboardAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.StandbyPowerSwitchForDashboardAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m StandbyPowerSwitchForDashboard) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.SwitchForDashboard)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.StandbyPowerSwitchForDashboardAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.StandbyPowerSwitchForDashboardAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this standby power switch for dashboard
func (m *StandbyPowerSwitchForDashboard) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SwitchForDashboard
	if err := m.SwitchForDashboard.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with StandbyPowerSwitchForDashboardAllOf1
	// validation for a type composition with StandbyPowerSwitchForDashboardAllOf2

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StandbyPowerSwitchForDashboard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StandbyPowerSwitchForDashboard) UnmarshalBinary(b []byte) error {
	var res StandbyPowerSwitchForDashboard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// StandbyPowerSwitchForDashboardAllOf1 standby power switch for dashboard all of1
//
// swagger:model StandbyPowerSwitchForDashboardAllOf1
type StandbyPowerSwitchForDashboardAllOf1 interface{}

// StandbyPowerSwitchForDashboardAllOf2 A button switch in the UI. Similar to the `toggleSwitch` displayType except for the `off` state is replaced by `standby`.
//
// swagger:model StandbyPowerSwitchForDashboardAllOf2
type StandbyPowerSwitchForDashboardAllOf2 interface{}
