// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StandbyPowerSwitch standby power switch
//
// swagger:model standbyPowerSwitch
type StandbyPowerSwitch struct {
	Switch

	StandbyPowerSwitchAllOf1

	StandbyPowerSwitchAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *StandbyPowerSwitch) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Switch
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Switch = aO0

	// AO1
	var aO1 StandbyPowerSwitchAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.StandbyPowerSwitchAllOf1 = aO1

	// AO2
	var aO2 StandbyPowerSwitchAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.StandbyPowerSwitchAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m StandbyPowerSwitch) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.Switch)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.StandbyPowerSwitchAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.StandbyPowerSwitchAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this standby power switch
func (m *StandbyPowerSwitch) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Switch
	if err := m.Switch.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with StandbyPowerSwitchAllOf1
	// validation for a type composition with StandbyPowerSwitchAllOf2

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StandbyPowerSwitch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StandbyPowerSwitch) UnmarshalBinary(b []byte) error {
	var res StandbyPowerSwitch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// StandbyPowerSwitchAllOf1 standby power switch all of1
//
// swagger:model StandbyPowerSwitchAllOf1
type StandbyPowerSwitchAllOf1 interface{}

// StandbyPowerSwitchAllOf2 A button switch in the UI. Similar to the `toggleSwitch` displayType except for the `off` state is replaced by `standby`.
//
// swagger:model StandbyPowerSwitchAllOf2
type StandbyPowerSwitchAllOf2 interface{}
