// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Step The incremental step that increases or decreases for numeric values.
//
// swagger:model step
type Step float64

// Validate validates this step
func (m Step) Validate(formats strfmt.Registry) error {
	return nil
}
