// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SubscriptionFilterAttributes subscription filter attributes
//
// swagger:model SubscriptionFilterAttributes
type SubscriptionFilterAttributes []string

// Validate validates this subscription filter attributes
func (m SubscriptionFilterAttributes) Validate(formats strfmt.Registry) error {
	return nil
}
