// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SubscriptionFilterEventTypes subscription filter event types
//
// swagger:model SubscriptionFilterEventTypes
type SubscriptionFilterEventTypes []string

// Validate validates this subscription filter event types
func (m SubscriptionFilterEventTypes) Validate(formats strfmt.Registry) error {
	return nil
}
