// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SubscriptionFilterValues An array of subscription filter values.
//
// swagger:model SubscriptionFilterValues
type SubscriptionFilterValues []string

// Validate validates this subscription filter values
func (m SubscriptionFilterValues) Validate(formats strfmt.Registry) error {
	return nil
}
