// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwitchForDashboard switch for dashboard
//
// swagger:model switchForDashboard
type SwitchForDashboard struct {
	SwitchForDashboardAllOf0

	SwitchCommand

	SwitchStateForDashboard

	SwitchForDashboardAllOf3
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SwitchForDashboard) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SwitchForDashboardAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SwitchForDashboardAllOf0 = aO0

	// AO1
	var aO1 SwitchCommand
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SwitchCommand = aO1

	// AO2
	var aO2 SwitchStateForDashboard
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.SwitchStateForDashboard = aO2

	// AO3
	var aO3 SwitchForDashboardAllOf3
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.SwitchForDashboardAllOf3 = aO3

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SwitchForDashboard) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 4)

	aO0, err := swag.WriteJSON(m.SwitchForDashboardAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SwitchCommand)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.SwitchStateForDashboard)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.SwitchForDashboardAllOf3)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this switch for dashboard
func (m *SwitchForDashboard) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SwitchForDashboardAllOf0
	// validation for a type composition with SwitchCommand
	if err := m.SwitchCommand.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SwitchStateForDashboard
	if err := m.SwitchStateForDashboard.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SwitchForDashboardAllOf3

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SwitchForDashboard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchForDashboard) UnmarshalBinary(b []byte) error {
	var res SwitchForDashboard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SwitchForDashboardAllOf0 This switch will display as a slider style on/off switch in the UI
//
// swagger:model SwitchForDashboardAllOf0
type SwitchForDashboardAllOf0 interface{}

// SwitchForDashboardAllOf3 switch for dashboard all of3
//
// swagger:model SwitchForDashboardAllOf3
type SwitchForDashboardAllOf3 interface{}
