// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SwitchState switch state
//
// swagger:model switchState
type SwitchState struct {

	// state
	State *SwitchStateState `json:"state,omitempty"`
}

// Validate validates this switch state
func (m *SwitchState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwitchState) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if m.State != nil {
		if err := m.State.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("state")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SwitchState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchState) UnmarshalBinary(b []byte) error {
	var res SwitchState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SwitchStateState To describe "on" and "off" state of a switch
//
// swagger:model SwitchStateState
type SwitchStateState struct {

	// alternatives
	Alternatives Alternatives `json:"alternatives,omitempty"`

	// label
	Label FormattedLabel `json:"label,omitempty"`

	// The attribute value that corresponds to the `off` state.
	// Required: true
	Off *string `json:"off"`

	// The attribute value that corresponds to the `on` state.
	// Required: true
	On *string `json:"on"`

	// value
	// Required: true
	Value Value `json:"value"`
}

// Validate validates this switch state state
func (m *SwitchStateState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlternatives(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOff(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwitchStateState) validateAlternatives(formats strfmt.Registry) error {

	if swag.IsZero(m.Alternatives) { // not required
		return nil
	}

	if err := m.Alternatives.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state" + "." + "alternatives")
		}
		return err
	}

	return nil
}

func (m *SwitchStateState) validateLabel(formats strfmt.Registry) error {

	if swag.IsZero(m.Label) { // not required
		return nil
	}

	if err := m.Label.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state" + "." + "label")
		}
		return err
	}

	return nil
}

func (m *SwitchStateState) validateOff(formats strfmt.Registry) error {

	if err := validate.Required("state"+"."+"off", "body", m.Off); err != nil {
		return err
	}

	return nil
}

func (m *SwitchStateState) validateOn(formats strfmt.Registry) error {

	if err := validate.Required("state"+"."+"on", "body", m.On); err != nil {
		return err
	}

	return nil
}

func (m *SwitchStateState) validateValue(formats strfmt.Registry) error {

	if err := m.Value.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state" + "." + "value")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SwitchStateState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchStateState) UnmarshalBinary(b []byte) error {
	var res SwitchStateState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
