// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ToggleSwitch toggle switch
//
// swagger:model toggleSwitch
type ToggleSwitch struct {
	ToggleSwitchAllOf0

	Switch

	ToggleSwitchAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ToggleSwitch) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ToggleSwitchAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ToggleSwitchAllOf0 = aO0

	// AO1
	var aO1 Switch
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.Switch = aO1

	// AO2
	var aO2 ToggleSwitchAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.ToggleSwitchAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ToggleSwitch) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.ToggleSwitchAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.Switch)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.ToggleSwitchAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this toggle switch
func (m *ToggleSwitch) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ToggleSwitchAllOf0
	// validation for a type composition with Switch
	if err := m.Switch.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ToggleSwitchAllOf2

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ToggleSwitch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ToggleSwitch) UnmarshalBinary(b []byte) error {
	var res ToggleSwitch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ToggleSwitchAllOf0 A button style switch element for the UI.
//
// swagger:model ToggleSwitchAllOf0
type ToggleSwitchAllOf0 interface{}

// ToggleSwitchAllOf2 toggle switch all of2
//
// swagger:model ToggleSwitchAllOf2
type ToggleSwitchAllOf2 interface{}
