// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ToggleSwitchForDashboard toggle switch for dashboard
//
// swagger:model toggleSwitchForDashboard
type ToggleSwitchForDashboard struct {
	ToggleSwitchForDashboardAllOf0

	SwitchForDashboard

	ToggleSwitchForDashboardAllOf2

	ToggleSwitchForDashboardAllOf3
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ToggleSwitchForDashboard) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ToggleSwitchForDashboardAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ToggleSwitchForDashboardAllOf0 = aO0

	// AO1
	var aO1 SwitchForDashboard
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SwitchForDashboard = aO1

	// AO2
	var aO2 ToggleSwitchForDashboardAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.ToggleSwitchForDashboardAllOf2 = aO2

	// AO3
	var aO3 ToggleSwitchForDashboardAllOf3
	if err := swag.ReadJSON(raw, &aO3); err != nil {
		return err
	}
	m.ToggleSwitchForDashboardAllOf3 = aO3

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ToggleSwitchForDashboard) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 4)

	aO0, err := swag.WriteJSON(m.ToggleSwitchForDashboardAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SwitchForDashboard)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.ToggleSwitchForDashboardAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	aO3, err := swag.WriteJSON(m.ToggleSwitchForDashboardAllOf3)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO3)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this toggle switch for dashboard
func (m *ToggleSwitchForDashboard) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ToggleSwitchForDashboardAllOf0
	// validation for a type composition with SwitchForDashboard
	if err := m.SwitchForDashboard.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ToggleSwitchForDashboardAllOf2
	// validation for a type composition with ToggleSwitchForDashboardAllOf3

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ToggleSwitchForDashboard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ToggleSwitchForDashboard) UnmarshalBinary(b []byte) error {
	var res ToggleSwitchForDashboard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ToggleSwitchForDashboardAllOf0 A button style switch element for the UI.
//
// swagger:model ToggleSwitchForDashboardAllOf0
type ToggleSwitchForDashboardAllOf0 interface{}

// ToggleSwitchForDashboardAllOf2 toggle switch for dashboard all of2
//
// swagger:model ToggleSwitchForDashboardAllOf2
type ToggleSwitchForDashboardAllOf2 interface{}

// ToggleSwitchForDashboardAllOf3 toggle switch for dashboard all of3
//
// swagger:model ToggleSwitchForDashboardAllOf3
type ToggleSwitchForDashboardAllOf3 interface{}
