// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ValueType The data type of the `value`. It's automatically filled from the given capability.
//
// swagger:model valueType
type ValueType string

// Validate validates this value type
func (m ValueType) Validate(formats strfmt.Registry) error {
	return nil
}
