// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WeatherEvent An event representing the current weather forecast.
//
// swagger:model WeatherEvent
type WeatherEvent struct {

	// air quality data
	AirQualityData *AirQualityData `json:"airQualityData,omitempty"`

	// weather data
	WeatherData *WeatherData `json:"weatherData,omitempty"`
}

// Validate validates this weather event
func (m *WeatherEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAirQualityData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWeatherData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WeatherEvent) validateAirQualityData(formats strfmt.Registry) error {

	if swag.IsZero(m.AirQualityData) { // not required
		return nil
	}

	if m.AirQualityData != nil {
		if err := m.AirQualityData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("airQualityData")
			}
			return err
		}
	}

	return nil
}

func (m *WeatherEvent) validateWeatherData(formats strfmt.Registry) error {

	if swag.IsZero(m.WeatherData) { // not required
		return nil
	}

	if m.WeatherData != nil {
		if err := m.WeatherData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("weatherData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WeatherEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeatherEvent) UnmarshalBinary(b []byte) error {
	var res WeatherEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
